version: '2'
services:
  redis:
    image: redis:latest
    
  myapp:
    image: eramonk/todo:latest
    container_name: todo 
    ports:
      - 9050:9050
    network_mode: "host"
   
  elasticsearch1:
    image: composetest_elasticsearch1
    build: ./elastic
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    network_mode: "host"
  elasticsearch2:
    image: composetest_elasticsearch2
    build: ./elastic
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    network_mode: "host"
    #networks:
    #  - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
