version: '3'
services:
  redis:
    image: redis:latest

  myapp:
    image: eramonk/todo:latest
    ports:
      - ${PORT}:9050
      - 8088:80
    volumes:
      - /home/ra/test/todo/chef:/home/
      - /home/ra/test/todo/docker/init.sh:/home/init.sh

  elasticsearch:
    image: elasticsearch
    build: ./elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#      - 9300:9300

volumes:
  esdata1:
    driver: local




