version: '3'
services:
  redis:
    image: redis:latest
#    container_name: redis
#    network_mode: "host"
#    ports:
#          - 6379:6379
#    expose:
#      - "6379"
  myapp:
    image: eramonk/todo:latest
#
#    expose:
#      - 9050
    ports:
      - ${PORT}:9050
    volumes:
      - /home/ra/test/todo/chef:/home/
#    network_mode: "host"

  elasticsearch:
    image: elasticsearch
    build: ./elasticsearch
#    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    mem_limit: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
#    network_mode: "host"
#    expose:
#       - 9200
#    ports:
#      - 9200:9200

volumes:
  esdata1:
    driver: local
#  esdata2:
#    driver: local

#networks:
#  esnet:
